loglevel = "info"
port = 8080

[redis]
host = "localhost"
port = 6379

[pg]
host = "localhost"
port = 5432
username = "postgres"
password = "postgres"
dbname = "postgres"
sslmode = "disable"

[oauth]
google.client.id=""
google.client.secret=""